In [63]:
import pandas as pd
import numpy as np
import pylab as P

# For .read_csv, always use header=0 when you know row 0 is the header row
df = pd.read_csv('train.csv', header=0)

In [64]:
df['Gender'] = df['Sex'].map( lambda x: x[0].upper() )


In [65]:
df['Gender'] = df['Sex'].map( {'female':0, 'male':1} ).astype(np.int)
df['Departure'] = df['Embarked'].map( {'S':0,'C':1,'Q':2})


In [66]:
df.loc[ df['Departure'].isnull(),'Departure' ] = 3
df['Departure'].unique()

array([ 0.,  1.,  2.,  3.])

In [67]:
median_ages = np.zeros((2,3))
median_ages

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [68]:
# calculate median ages according to class and gender
for i in range(2):
    for j in range(3):
        median_ages[i,j] = df[ (df['Gender'] == i) & (df['Pclass'] == j+1) ] ['Age'].dropna().median()
median_ages

df['Agefill']= df.Age

for i in range(0, 2):
    for j in range(0, 3):
        df.loc[ (df.Age.isnull()) & (df.Gender == i) & (df.Pclass == j+1),'Agefill'] = median_ages[i,j]
 

In [69]:
df['AgeIsNull'] = pd.isnull(df.Age).astype(int)

In [70]:
df['FamilySize'] = df['SibSp'] + df['Parch']
df['Age*Class'] = df.Agefill * df.Pclass


In [71]:
df = df.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked','PassengerId'], axis=1) 
df = df.drop(['Age'], axis=1)


In [72]:
df.head()

Survived  Pclass  SibSp  Parch     Fare  Gender  Departure  Agefill  \
0         0       3      1      0   7.2500       1          0       22   
1         1       1      1      0  71.2833       0          1       38   
2         1       3      0      0   7.9250       0          0       26   
3         1       1      1      0  53.1000       0          0       35   
4         0       3      0      0   8.0500       1          0       35   

   AgeIsNull  FamilySize  Age*Class  
0          0           1         66  
1          0           1         38  
2          0           0         78  
3          0           1         35  
4          0           0        105

In [73]:
train_data = df.values

In [74]:
x = train_data.astype(float)

In [75]:
x

array([[  0. ,   3. ,   1. , ...,   0. ,   1. ,  66. ],
       [  1. ,   1. ,   1. , ...,   0. ,   1. ,  38. ],
       [  1. ,   3. ,   0. , ...,   0. ,   0. ,  78. ],
       ..., 
       [  0. ,   3. ,   1. , ...,   1. ,   3. ,  64.5],
       [  1. ,   1. ,   0. , ...,   0. ,   0. ,  26. ],
       [  0. ,   3. ,   0. , ...,   0. ,   0. ,  96. ]])

In [76]:
# Import the random forest package
from sklearn.ensemble import RandomForestClassifier 

# Create the random forest object which will include all the parameters
# for the fit
forest = RandomForestClassifier(n_estimators = 100)

# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(train_data[0::,1::],train_data[0::,0])



In [77]:
ytrain = forest.predict(train_data[0::,1::])

In [81]:
forest.score(train_data[0::,1::],train_data[0::,0])

0.98204264870931535

In [85]:
dftest = pd.read_csv("test.csv")

In [91]:
dftest.head(2)

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

   Parch  Ticket    Fare Cabin Embarked  Gender  
0      0  330911  7.8292   NaN        Q       1  
1      0  363272  7.0000   NaN        S       0

In [104]:
dftest['Gender']=dftest['Sex'].map({'female':0,'male':1}).astype(int)
dftest['Departure'] = dftest['Embarked'].map({'S':0,'C':1,'Q':2})
dftest['Agefill']=dftest['Age']


In [106]:
for i in range(0, 2):
    for j in range(0, 3):
        dftest.loc[ (dftest.Age.isnull()) & (dftest.Gender == i) & (dftest.Pclass == j+1),'Agefill'] = median_ages[i,j]
 

In [109]:
dftest['AgeisNull'] = pd.isnull(dftest['Age']).astype(int)
dftest['FamilySize'] = dftest['Parch']+dftest['SibSp']
dftest['Age*Class'] = dftest['Agefill']*dftest['Pclass']

In [111]:
dftest = dftest.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked','PassengerId'], axis=1) 
dftest = dftest.drop(['Age'], axis=1)

In [112]:
dftest.head()

Pclass  SibSp  Parch     Fare  Gender  Departure  Agefill  AgeisNull  \
0       3      0      0   7.8292       1          2     34.5          0   
1       3      1      0   7.0000       0          0     47.0          0   
2       2      0      0   9.6875       1          2     62.0          0   
3       3      0      0   8.6625       1          0     27.0          0   
4       3      1      1  12.2875       0          0     22.0          0   

   FamilySize  Age*Class  
0           0      103.5  
1           1      141.0  
2           0      124.0  
3           0       81.0  
4           2       66.0

In [129]:
df.head()

Survived  Pclass  SibSp  Parch     Fare  Gender  Departure  Agefill  \
0         0       3      1      0   7.2500       1          0       22   
1         1       1      1      0  71.2833       0          1       38   
2         1       3      0      0   7.9250       0          0       26   
3         1       1      1      0  53.1000       0          0       35   
4         0       3      0      0   8.0500       1          0       35   

   AgeIsNull  FamilySize  Age*Class  
0          0           1         66  
1          0           1         38  
2          0           0         78  
3          0           1         35  
4          0           0        105

In [163]:
testvalue = dftest.values

In [164]:
testvalue = testvalue.astype(float)

In [143]:
dftest[dftest['Fare'].isnull()]

Pclass  SibSp  Parch  Fare  Gender  Departure  Agefill  AgeisNull  \
152       3      0      0   NaN       1          0     60.5          0   

     FamilySize  Age*Class  
152           0      181.5

In [157]:
dftest['Fare'].hist()
P.show()


14.4542

In [161]:
dftest.loc[dftest['Fare'].isnull(),'Fare'] = dftest['Fare'].median()

In [162]:
dftest.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 10 columns):
Pclass        418 non-null int64
SibSp         418 non-null int64
Parch         418 non-null int64
Fare          418 non-null float64
Gender        418 non-null int64
Departure     418 non-null int64
Agefill       418 non-null float64
AgeisNull     418 non-null int64
FamilySize    418 non-null int64
Age*Class     418 non-null float64
dtypes: float64(3), int64(7)
memory usage: 35.9 KB


In [165]:
result = forest.predict(testvalue)

In [192]:
resultdf = pd.DataFrame(dftest2['PassengerId'])

In [210]:
resultdf['Survived'] = result.astype(int)

In [212]:
resultdf.to_csv('randomforest.csv',index=False)

In [178]:
dftest2.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [211]:
resultdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 2 columns):
PassengerId    418 non-null int64
Survived       418 non-null int64
dtypes: int64(2)
memory usage: 9.8 KB


In [205]:
gbm = pd.read_csv('genderbasedmodel.csv')

In [206]:
gbm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 2 columns):
PassengerId    418 non-null int64
Survived       418 non-null int64
dtypes: int64(2)
memory usage: 9.8 KB
